import {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  AtSign,
  AudioLines,
  Bell,
  BellRing,
  BarChart3,
  BookUser,
  Bot,
  BookOpen,
  Braces,
  Briefcase,
  Building2,
  Calendar,
  CalendarDays,
  CalendarPlus,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cloud,
  CloudCheck,
  CloudUpload,
  Code2,
  Copy,
  CreditCard,
  Cpu,
  Database,
  Download,
  Eye,
  ExternalLink,
  FileCode,
  FilePenLine,
  FileText,
  FileUp,
  FlaskConical,
  Frown,
  Globe,
  Headset,
  HelpCircle,
  History,
  Hourglass,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Link2,
  ListChecks,
  ListFilter,
  LogOut,
  type LucideIcon,
  Mail,
  MailCheck,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Meh,
  Mic,
  Mic2,
  Minus,
  MinusCircle,
  MoreHorizontal,
  MoreVertical,
  Moon,
  Palette,
  PanelLeftClose,
  PauseCircle,
  Phone,
  PhoneForwarded,
  PhoneOff,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  Radio,
  RefreshCcw,
  RefreshCcwDot,
  RefreshCw,
  Rocket,
  Search,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Sliders,
  Smartphone,
  Smile,
  Sparkles,
  Speech,
  Store,
  Table,
  Tag,
  Target,
  Terminal,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  Truck,
  UserMinus,
  UserPlus,
  UserSearch,
  Users,
  Users2,
  Voicemail,
  VolumeX,
  Waves,
  Webhook,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Maps the Material Symbols Outlined icon names used throughout the
 * Stitch design exports onto their closest Lucide equivalent, so ported
 * markup keeps using the same semantic names (e.g. "smart_toy", "call").
 */
export const iconMap: Record<string, LucideIcon> = {
  account_tree: Share2,
  add: Plus,
  add_circle: PlusCircle,
  adjust: Target,
  alternate_email: AtSign,
  analytics: BarChart3,
  api: Braces,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  article: FileText,
  avg_time: Timer,
  bar_chart: BarChart3,
  bolt: Zap,
  build: Wrench,
  business: Building2,
  calendar_add_on: CalendarPlus,
  calendar_month: Calendar,
  calendar_today: CalendarDays,
  call: Phone,
  call_end: PhoneOff,
  call_merge: PhoneForwarded,
  campaign: Zap,
  chat: MessageCircle,
  chat_bubble: MessageSquare,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  cloud: Cloud,
  cloud_done: CloudCheck,
  cloud_upload: CloudUpload,
  code: Code2,
  content_copy: Copy,
  dark_mode: Moon,
  dashboard: LayoutDashboard,
  data_object: Braces,
  database: Database,
  delete: Trash2,
  description: FileText,
  domain: Building2,
  download: Download,
  east: ArrowRight,
  edit_note: FilePenLine,
  experiment: FlaskConical,
  filter_list: ListFilter,
  forum: MessagesSquare,
  graphic_eq: AudioLines,
  group: Users,
  groups: Users2,
  help: HelpCircle,
  history: History,
  hourglass_empty: Hourglass,
  hub: Share2,
  info: Info,
  insights: Lightbulb,
  javascript: FileCode,
  keyboard_arrow_down: ChevronDown,
  label: Tag,
  language: Globe,
  layers: Layers,
  leaderboard: Trophy,
  library_books: BookOpen,
  link: Link2,
  local_shipping: Truck,
  logout: LogOut,
  mail: Mail,
  mark_email_read: MailCheck,
  memory: Cpu,
  menu_open: PanelLeftClose,
  mic: Mic,
  more_horiz: MoreHorizontal,
  more_vert: MoreVertical,
  notifications: Bell,
  notifications_active: BellRing,
  open_in_new: ExternalLink,
  palette: Palette,
  pause_circle: PauseCircle,
  payments: CreditCard,
  person_add: UserPlus,
  person_remove: UserMinus,
  person_search: UserSearch,
  picture_as_pdf: FileText,
  play_arrow: Play,
  play_circle: PlayCircle,
  podcasts: Radio,
  record_voice_over: Mic2,
  refresh: RefreshCw,
  remove: Minus,
  remove_circle: MinusCircle,
  rocket_launch: Rocket,
  schedule: Clock,
  search: Search,
  security: ShieldCheck,
  sensors: Radio,
  shield: Shield,
  sentiment_dissatisfied: Frown,
  sentiment_neutral: Meh,
  sentiment_satisfied: Smile,
  settings: Settings,
  settings_voice: Settings2,
  shopping_cart: ShoppingCart,
  show_chart: TrendingUp,
  contacts: BookUser,
  smart_toy: Bot,
  smartphone: Smartphone,
  south: ArrowDown,
  spatial_audio_off: VolumeX,
  stars: Sparkles,
  storefront: Store,
  stream: Waves,
  support_agent: Headset,
  sync: RefreshCcw,
  sync_problem: RefreshCcwDot,
  table_chart: Table,
  task_alt: ListChecks,
  terminal: Terminal,
  timer: Timer,
  trending_up: TrendingUp,
  upload_file: FileUp,
  visibility: Eye,
  voice_chat: Speech,
  voice_selection: Sliders,
  voicemail: Voicemail,
  vpn_key: KeyRound,
  warning: AlertTriangle,
  webhook: Webhook,
  work: Briefcase,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? AlertCircle;
}
